# Stages of pipeline, should match with stage tag inside each job.
# Each stages executes in sequence, if previous job fails, then all the preceeding jobs are skipped.
stages:
  - mavenbuild
  - maventest
  - autodeploy
  - androidbuild
  - androidtest

# tags: "shell" should match with the tag name provided to runner, for spring runner should execute in shell.
# Notice that in petclinic project, the spring project is in root of master, if yours is in folder then cd to that folder.
#TODO: IF THERE ARE ERRORS OCCURING TRY CHANGING THIS TAG
maven-build:
  stage: mavenbuild
  tags:
    - spring_tag
  script:
    - cd Backend/calendar
    - mvn package -B
  
# artifacts are created when job executes successfully, and can be manually downloaded from GitLab GUI.
# artifacts are not mandatory, buts it good practice, in case auto deploy fails, you can manually download the jar.
maven-test:
  stage: maventest
  tags:
    - spring_tag
  script:
    - cd Backend/calendar
    - mvn test
  artifacts:
    paths:
      - Backend/calendar/target/*.jar
# Below stage builds, deploys and executes the jar as service.
# Make sure there is /target directory in your server, else script will fail, or use any other folder you like.
# If you are changing the folder, reflect the change in systemd-web-demo service too.
autoDeploy:
  stage: autodeploy
  tags:
   - spring_tag
  script:
    - cd Backend/calendar
    - mvn package
    - sudo mv target/*.jar /var/www/html/system-web-demo.jar 
    - sudo systemctl stop system-web-demo
    - sudo systemctl start system-web-demo

    
# To build android projects 
# Notice that we cd into Android_test folder which contains all Android files before building apk.    
# Ensure the tag matches with the tag created for Android runner
# Android runner should have docker as executor.
android-build:
  image: javiersantos/android-ci:latest
  stage: androidbuild
  before_script:
    - export GRADLE_USER_HOME=`pwd`/.gradle
    - chmod +x ./FrontEnd/Ili/gradlew
  tags:
   - android_tag
  script:
    - cd FrontEnd/Ili
    - ./gradlew assemble
  artifacts:
    paths:
    - FrontEnd/Ili/app/build/outputs/
    
# To run Android unit tests.   
unitTests:
  image: javiersantos/android-ci:latest
  stage: androidtest
  before_script:
    - export GRADLE_USER_HOME=`pwd`/.gradle
    - chmod +x ./FrontEnd/Ili/gradlew
  tags:
   - android_tag
  script:
    - cd FrontEnd/Ili
    - ./gradlew test
